/// IDNA-2003 `ToASCII`, standing in for `java.net.IDN.toASCII`.
///
/// Deliberately IDNA-2003 (RFC 3490 with RFC 3491 nameprep), *not* IDNA-2008 or
/// UTS-46, because that is what the JDK implements and what Commons Validator's
/// behaviour is defined against. The three disagree on characters such as
/// `sharp s`, final sigma and the zero-width joiners.
///
/// Rather than hand-write the RFC 3454 tables, everything in `idna_data.dart` is
/// generated by measuring the reference JDK: the case folds by round-tripping
/// each code point through `IDN.toASCII` and `IDN.toUnicode`, the rejected code
/// points by asking which ones it refuses, and the bidirectional classes from
/// `Character.getDirectionality`. See that file and `tool/generate_idna_data.dart`.
library;

import 'package:unorm_dart/unorm_dart.dart' as unorm;

import 'ascii.dart';
import 'idna_data.dart';
import 'punycode.dart';

/// The `xn--` prefix marking a punycoded label.
const String acePrefix = 'xn--';

/// The maximum length of a single DNS label, in octets.
const int maxLabelLength = 63;

/// Thrown when a string cannot be converted, mirroring the
/// `IllegalArgumentException` that `IDN.toASCII` throws.
class IdnaException implements Exception {
  /// Creates an exception with [message].
  const IdnaException(this.message);

  /// What went wrong.
  final String message;

  @override
  String toString() => 'IdnaException: $message';
}

/// Whether [codeUnit] is one of the four separators RFC 3490 section 3.1
/// requires be recognised as a label separator.
bool isLabelSeparator(int codeUnit) =>
    codeUnit == 0x002E || // FULL STOP
    codeUnit == 0x3002 || // IDEOGRAPHIC FULL STOP
    codeUnit == 0xFF0E || // FULLWIDTH FULL STOP
    codeUnit == 0xFF61; // HALFWIDTH IDEOGRAPHIC FULL STOP

/// Converts [input] to its ASCII Compatible Encoding.
///
/// Throws [IdnaException] where the JDK throws `IllegalArgumentException`:
/// an empty or over-long label, an unassigned or prohibited code point, or a
/// punycode overflow.
String toAscii(String input) {
  if (input.isEmpty) return input;

  // A single trailing separator is the trailing dot of a rooted name and is
  // kept; every other label must be non-empty. Probing the JDK gives
  // `.` -> `.`, `a.` -> `a.`, `a.b.` -> `a.b.`, but `..`, `.a` and `a..b` all
  // throw, and this model reproduces exactly that.
  final hasTrailingDot = isLabelSeparator(input.codeUnitAt(input.length - 1));
  final body = hasTrailingDot ? input.substring(0, input.length - 1) : input;
  if (body.isEmpty) return '.';

  final converted = _splitLabels(body).map(_labelToAscii).join('.');
  return hasTrailingDot ? '$converted.' : converted;
}

/// Splits on any of the four separators, keeping empty labels so that a trailing
/// dot survives the round trip.
List<String> _splitLabels(String input) {
  final labels = <String>[];
  final buffer = StringBuffer();
  for (final unit in input.codeUnits) {
    if (isLabelSeparator(unit)) {
      labels.add(buffer.toString());
      buffer.clear();
    } else {
      buffer.writeCharCode(unit);
    }
  }
  labels.add(buffer.toString());
  return labels;
}

String _labelToAscii(String label) {
  if (label.isEmpty) {
    throw const IdnaException('Empty label is not a legal name');
  }

  // An all-ASCII label needs only the length check. This is also what leaves an
  // already-encoded `xn--` label untouched.
  if (isOnlyAscii(label)) {
    _checkLength(label);
    return label;
  }

  final prepared = nameprep(label);
  if (prepared.isEmpty) {
    throw const IdnaException('Empty label is not a legal name');
  }

  // Nameprep can fold a label down to pure ASCII - `strasse` from the sharp-s
  // spelling - in which case there is nothing to punycode.
  if (isOnlyAscii(prepared)) {
    _checkLength(prepared);
    return prepared;
  }

  // RFC 3490 step 5: the string to be punycoded must not already begin with the
  // ACE prefix. Without this, `xn--exmple{e-acute}-cua` would be encoded a
  // second time into a valid-looking label, where the JDK rejects it.
  if (prepared.length >= acePrefix.length &&
      asciiToLowerCase(prepared.substring(0, acePrefix.length)) == acePrefix) {
    throw const IdnaException('The input starts with the ACE prefix');
  }

  final String encoded;
  try {
    encoded = '$acePrefix${punycodeEncode(prepared)}';
  } on PunycodeException catch (e) {
    throw IdnaException(e.message);
  }
  _checkLength(encoded);
  return encoded;
}

void _checkLength(String label) {
  if (label.length > maxLabelLength) {
    throw IdnaException('The label in the input is too long: $label');
  }
}

/// RFC 3491 nameprep: map and case-fold, normalize to NFKC, then reject
/// prohibited or unassigned output.
String nameprep(String label) {
  // The unassigned-code-point check is a property of the *input*: case folding
  // would otherwise erase the evidence, since U+1E9E (capital sharp s, added in
  // Unicode 5.1 and so unassigned as far as nameprep is concerned) folds to a
  // perfectly ordinary `ss`.
  _checkAllowed(label);
  final mapped = _mapCaseAndRemove(label);
  // Normalization can *produce* characters that still need folding: NFKC turns
  // U+2102 DOUBLE-STRUCK CAPITAL C into an upper-case `C` and U+03D2 into
  // upper-case Upsilon, and the JDK yields `c` and lower-case upsilon for them.
  //
  // The second pass applies only the *simple* (single code point) folds. Using
  // the full folds again would undo the composition NFKC just performed: the
  // full fold of U+0390 is iota + dialytika + tonos, which NFKC recomposes back
  // to U+0390, so folding a second time would decompose it for good.
  final normalized = _foldSimple(unorm.nfkc(mapped));
  _checkAllowed(normalized);
  _checkBidi(normalized);
  return normalized;
}

/// RFC 3454 section 6: a string containing any right-to-left character must not
/// also contain a left-to-right one, and must both start and end with a
/// right-to-left character.
///
/// The check runs after normalization because normalization is what makes it
/// bite: U+2135 ALEF SYMBOL is bidi class `L`, but NFKC maps it to U+05D0
/// HEBREW LETTER ALEF, which is class `R`. So `a<U+2135>b` is a mixed-direction
/// label even though every input character looks left-to-right.
void _checkBidi(String s) {
  if (s.isEmpty) return;
  final runes = s.runes.toList();
  final hasRandAL = runes.any(_isRandALCat);
  if (!hasRandAL) return;
  if (runes.any(_isLCat)) {
    throw const IdnaException(
      'The input contains both left-to-right and right-to-left characters',
    );
  }
  if (!_isRandALCat(runes.first) || !_isRandALCat(runes.last)) {
    throw const IdnaException(
      'A right-to-left string must start and end with a right-to-left character',
    );
  }
}

bool _isRandALCat(int cp) => _inRanges(bidiRandALCatRanges, cp);

bool _isLCat(int cp) => _inRanges(bidiLCatRanges, cp);

/// Applies RFC 3454 Table B.1 (map to nothing) and Table B.2 (full case
/// folding), the latter from the generated tables rather than
/// [String.toLowerCase].
String _mapCaseAndRemove(String label) {
  final out = <int>[];
  for (final cp in label.runes) {
    if (_mapsToNothing(cp)) continue;
    // A fold whose target is unassigned as far as nameprep is concerned cannot
    // have existed in Unicode 3.2 either, so the JDK does not apply it. U+2132
    // is the case in point: newer Unicode folds it to U+214E, which Unicode 3.2
    // does not assign, and the JDK therefore leaves U+2132 alone.
    final single = caseFoldingSingle[cp];
    if (single != null) {
      out.add(_isRejected(single) ? cp : single);
      continue;
    }
    final multi = caseFoldingMulti[cp];
    if (multi != null) {
      if (multi.any(_isRejected)) {
        out.add(cp);
      } else {
        out.addAll(multi);
      }
      continue;
    }
    out.add(cp);
  }
  return String.fromCharCodes(out);
}

/// Applies only the single-code-point case folds, leaving the multi-code-point
/// ones alone. See the second-pass comment in [nameprep].
String _foldSimple(String s) {
  final out = <int>[];
  for (final cp in s.runes) {
    final folded = caseFoldingSingle[cp];
    // Same suppression as the first pass: a fold onto a code point nameprep
    // treats as unassigned did not exist in Unicode 3.2 either.
    out.add(folded == null || _isRejected(folded) ? cp : folded);
  }
  return String.fromCharCodes(out);
}

/// RFC 3454 Table B.1: code points nameprep deletes.
bool _mapsToNothing(int cp) =>
    cp == 0x00AD || // SOFT HYPHEN
    cp == 0x034F || // COMBINING GRAPHEME JOINER
    cp == 0x1806 || // MONGOLIAN TODO SOFT HYPHEN
    (cp >= 0x180B && cp <= 0x180D) || // MONGOLIAN FREE VARIATION SELECTORs
    (cp >= 0x200B && cp <= 0x200D) || // ZWSP, ZWNJ, ZWJ
    cp == 0x2060 || // WORD JOINER
    (cp >= 0xFE00 && cp <= 0xFE0F) || // VARIATION SELECTOR-1..16
    cp == 0xFEFF; // ZERO WIDTH NO-BREAK SPACE

/// Rejects code points the JDK rejects: RFC 3454 Table A.1 (unassigned in
/// Unicode 3.2) and the C.* prohibited-output tables.
///
/// This matters for more than tidiness. `IDN.toASCII` throws for these, and
/// `DomainValidator` then keeps the original non-ASCII input so its label regex
/// rejects it. Without the check a prohibited code point would be punycoded into
/// innocent-looking ASCII and the host would *validate*.
void _checkAllowed(String s) {
  for (final cp in s.runes) {
    if (_isRejected(cp)) {
      throw IdnaException(
        'Prohibited or unassigned code point '
        'U+${cp.toRadixString(16).toUpperCase()}',
      );
    }
  }
}

bool _isRejected(int cp) => _inRanges(idnRejectedRanges, cp);

/// Binary search over a flat `[low, high, low, high, ...]` range table.
bool _inRanges(List<int> ranges, int cp) {
  var low = 0;
  var high = ranges.length ~/ 2 - 1;
  while (low <= high) {
    final mid = (low + high) >> 1;
    if (cp < ranges[mid * 2]) {
      high = mid - 1;
    } else if (cp > ranges[mid * 2 + 1]) {
      low = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}
